# Generated by Django 4.2.16 on 2024-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='email',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default=1, upload_to='artist/'),
            preserve_default=False,
        ),
    ]
