# Generated by Django 4.2.16 on 2024-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, verbose_name='Описание жанра')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genre',
                'ordering': ['name'],
            },
        ),
    ]
